### ISSUE TITLE
执行一条龙是勾选了委托，但是实际运行的时候不会执行委托内容

### ISSUE THREAD

**Issue by smallmj** [DoctorReid/StarRailOneDragon#182]

**Comment by DoctorReid** [comment]
没日志无法判断

**Comment by smallmj** [comment]
没有保留日志，但是确实没有领取委托，把委托放在一条龙第一个执行，程序会跳过委托，直接执行第二项锄大地或者每日实训

**Comment by DoctorReid** [comment]
先升级 0.9.9。跳过有两种原因

1. 当天已经执行过一次了，当时没有红点。第二次不会再执行，这个在0.9.9版本应该改了。
2. 有接入米游社便签，便签数据显示还没有完成委托。

观察是否以上情况，如都不是，需要提供更多信息才能判断。

**Comment by smallmj** [comment]
![_1708407802687](https://github.com/DoctorReid/StarRailOneDragon/assets/23742160/aeb4b3e9-c0ba-45ec-b514-46780cce9c7e)
设定一条龙执行了委托，实际执行实在上午9点47分，我确定委托是在凌晨4点左右就完成了，但是程序不会执行委托脚本，整个一条龙运行完，委托都没有领取

**Comment by smallmj** [comment]
![_1708477577404](https://github.com/DoctorReid/StarRailOneDragon/assets/23742160/c96343f1-f598-4d4a-9e8c-c3157b36c467)
第二天执行委托依然失败，进入委托画面后，立马就会关掉委托界面，日志显示执行成功，但是奖励并没有领取

**Comment by smallmj** [comment]
claim_dt: '20240221'
dt: '20240221'
run_status: 1
run_time: 02-21 09:03   
run_time_float: 1708477420.68634  就这点内容

**Comment by DoctorReid** [comment]
你接的委托是多长时间的？

**Comment by smallmj** [comment]
20小时

**Comment by DoctorReid** [comment]
观察了两周，我都没出现类似的问题。你还有这样的问题吗
