### ISSUE TITLE
只要开了跑步选项，不管是打模拟宇宙还是锄大地，经常会出现跑过了的情况

### ISSUE THREAD

**Issue by smallmj** [DoctorReid/StarRailOneDragon#192]
锄大地的时候还好，无非就是被怪偷袭，但是打模拟宇宙的时候，经常跑过了传送门，来回找，有时候找不到还得暂离模拟宇宙，退出来重进，很浪费时间

**Comment by DoctorReid** [comment]
初步判断两种原因

1. 游戏画质不够好导致识别坐标失败，可以看看日志是否比较多显示 `无法判断当前人物坐标`，如果比较多可以考虑提高画质。
2. 机器运算较慢导致识别坐标运行过久，这个后续我会加个运行性能检测，再看大家的运行瓶颈在哪，再看怎么优化。

**Comment by DoctorReid** [comment]
将统一到 #207 进行
