### ISSUE TITLE
使用todesk连接PC后，如果显示器线没有插，或者笔记本合上盖子，程序将无法控制。插上显示器线但不用打开显示器，或者笔记本打开盖子，程序就恢复正常了

### ISSUE THREAD

**Issue by smallmj** [DoctorReid/StarRailOneDragon#194]

**Comment by DoctorReid** [comment]
我理解是这样的，脚本依赖的是图像识别，电脑必须要先有图像输出。

1. 笔记本合上盖子而没有连显示器线，完全没有图像输出，所以脚本无法识别。
2. 笔记本连了显示器线，但不用打开显示器。笔记本有对显示器线输出图像，只是显示器没有启动接收，脚本可以识别。

**Comment by qianxuu** [comment]
你需要购买一个 hdmi 欺骗器或者安装使用虚拟显示器驱动 https://github.com/nomi-san/parsec-vdd
