### ISSUE TITLE
有几个小怪经常漏掉，可以考虑改进下路线

### ISSUE THREAD

**Issue by jiafjioajfijaiofnkan** [DoctorReid/StarRailOneDragon#198]
![image](https://github.com/DoctorReid/StarRailOneDragon/assets/152603055/bb9f6b98-bb6f-47ae-8254-f8e362b033d2)
![image](https://github.com/DoctorReid/StarRailOneDragon/assets/152603055/f795e431-dee4-4735-b2a4-d4f67ab1dfaa)

**Comment by jiafjioajfijaiofnkan** [comment]
再补充一点：
![image](https://github.com/DoctorReid/StarRailOneDragon/assets/152603055/d7f268d2-0821-4101-b3a0-2ea65659ea0c)
![image](https://github.com/DoctorReid/StarRailOneDragon/assets/152603055/39ba955c-fb19-47f0-a22f-67dff2f2d8f2)

**Comment by jiafjioajfijaiofnkan** [comment]
![image](https://github.com/DoctorReid/StarRailOneDragon/assets/152603055/b6aa6561-e8bf-4559-a92d-23ad963cdd27)

**Comment by DoctorReid** [comment]
感谢提供，下次可以加入路线名称。或者使用路线绘制功能修改后上传

**Comment by jiafjioajfijaiofnkan** [comment]
> 感谢提供，下次可以加入路线名称。或者使用路线绘制功能修改后上传

以前画过新路线，但更新之后坐标好像变了，就被迫删除了。
修改的话比较坑，得一直删到对应坐标才能加新的点，所以只能画新的。

**Comment by DoctorReid** [comment]
右边的编辑框是可以用的，不过路线长改起来的确麻烦点
