### ISSUE TITLE
建议加上一个遇袭进战的自动识别

### ISSUE THREAD

**Issue by smallmj** [DoctorReid/StarRailOneDragon#200]
在模拟宇宙中，遇袭进战后，程序不会判断游戏正在战斗中，仍然在运行寻路脚本，导致超时终止。不清楚锄大地中是否会遇见同样的问题。

**Comment by DoctorReid** [comment]
都有这个判断的。模拟宇宙中应该是路线末尾会出现这个问题，日志中应该显示无法找到下层入口

**Comment by DoctorReid** [comment]
#204
