### ISSUE TITLE
一个通用的返回普通大世界的方法

### ISSUE THREAD

**Issue by DoctorReid** [DoctorReid/StarRailOneDragon#214]
目前脚本应用都需要从普通大世界画面进行启动，如果前一个指令出错导致卡在某个画面无法返回普通大世界画面，后续所有指令将无法进行，因此需要一个通用的返回方法。

需要考虑以下场景：

- 普通大世界场景
- 逐光捡金场景
- 模拟宇宙场景

**Comment by Clulu1499** [comment]
启动脚本时如果在2.0的三维地图里会导致一直尝试打开地图
![捉虫](https://github.com/DoctorReid/StarRailOneDragon/assets/72173120/b72e77d6-f3f3-4c7a-8557-f7fbaac62ef9)

**Comment by DoctorReid** [comment]
get

> 启动脚本时如果在2.0的三维地图里会导致一直尝试打开地图 ![捉虫](https://private-user-images.githubusercontent.com/72173120/310207373-b72e77d6-f3f3-4c7a-8557-f7fbaac62ef9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2OTA2NzUsIm5iZiI6MTcwOTY5MDM3NSwicGF0aCI6Ii83MjE3MzEyMC8zMTAyMDczNzMtYjcyZTc3ZDYtZjNmMy00YzdhLTg1NTctZjdmYmFhYzYyZWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDAxNTkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhMmRhMWZhYmNmNTcwMWJmZTcxMmZlYzhlNGU4MjZhOTY4YmRkODBkMjM0YWMyZTg1MTM0YzYyYjdmNGUxZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kFmMRC95SotwMpmGXreMAYCsM-ZBvAtidWV0nnvDGm0)
