### ISSUE TITLE
建议在2.1版本的锄地和模拟宇宙中增加使用黄泉秘技的功能

### ISSUE THREAD

**Issue by Furina113** [DoctorReid/StarRailOneDragon#227]
2.1黄泉秘技秒杀怪物能够极大提高锄地和刷模拟宇宙效率
实现该目标可能需要注意的点：
1.黄泉秘技为近战  需要更近的靠近怪物
2.需要自动补充秘技点

**Comment by DoctorReid** [comment]
会的

**Comment by Furina113** [comment]
> 会的

可秒杀怪物头上会有红色标记  可据此进行判定
可参考此视频08:19画面
https://www.bilibili.com/video/av1751838010/

**Comment by DoctorReid** [comment]
- [x] 连续使用消耗品
- [ ] 仅使用秘技开怪
- [ ] 朝最近的敌人方向攻击
