### ISSUE TITLE
软件内更新后将自行修改的锄大地路线信息全都覆盖了

### ISSUE THREAD

**Issue by bluemoon23333** [DoctorReid/StarRailOneDragon#232]
# 使用版本

1.1.1

# 问题描述

在软件内，设置中通过检查更新之后更新。
更新完成之后会将用户自行修改过的同名锄大地信息文件覆盖，导致自定义修改的配置失效。
<img width="636" alt="问题" src="https://github.com/DoctorReid/StarRailOneDragon/assets/129190788/f138fb04-be09-4aad-8355-e8624b5bef99">

**Comment by bluemoon23333** [comment]
建议更新时不要重新下载相同的锄大地路线信息文件
或者干脆添加软件内路线备份功能
我编辑了好久的路线都无了，只能看看能不能文件找回了，哎

**Comment by DoctorReid** [comment]
额，你的确是第一个要自己改路线的。你是大概修改了什么内容呢，是否可以将优化之后的路线提交贡献给大家使用

**Comment by bluemoon23333** [comment]
> 额，你的确是第一个要自己改路线的。你是大概修改了什么内容呢，是否可以将优化之后的路线提交贡献给大家使用

大概是优化了一些可能会卡墙的地方（比如禁闭舱段），以及增加了路上顺路一些可击碎物的收集
总共大概会比原来路线的时间多半个小时左右吧
调整了下一些路线的顺序，保证每条战斗路线开始前都会有锚点可以回血（因为我发现带两个低等级的角色练级会很容易死）
优化后的路线现在还差皮诺康妮的路线没弄
可能一周之内弄完吧，之后可以发在评论这里

**Comment by DoctorReid** [comment]
啊，这边刚好在调整路线适配近战角色，为了黄泉，你看方便加入 192920113 讨论下路线

**Comment by DoctorReid** [comment]
看了下目前框架不太好改，先自己备份好吧。目前需要优先开发第九宇宙的
