### ISSUE TITLE
请问米游社签到功能能否增加对米哈游其他游戏的支持,例如原神

### ISSUE THREAD

**Issue by UU0510** [DoctorReid/StarRailOneDragon#235]
# 使用版本

1.1.1

# 问题描述

如题, 应该有不少双修甚至三修玩家, 可否在星铁签到时顺带把原神也签了

**Comment by DoctorReid** [comment]
感觉这个签到成功率不是很高，后续考虑一下

**Comment by DoctorReid** [comment]
后续统一使用QQ群里的机器人签到，脚本不支持签到了
