### ISSUE TITLE
锄地路线精准定位及3D房间问题

### ISSUE THREAD

**Issue by yaoyan7788** [DoctorReid/StarRailOneDragon#241]
# 使用版本

1.1.2

# 问题分类

- `其他`

# 路线名称

# 问题描述

锄大地—路线绘制，部分新地图太大，因为预览固定了地图的大小，导致无法修改锄地路线无法精确定点。建议添加地图放大功能以改善近战角色锄地路线的精确定位问题。
另外，匹诺康尼中3D房间及交互机关增多，更多怪物投放在其中，且未来或有更多地图坐标无法定位的新地图，作者是否可考虑添加模拟按键功能改善相关问题。
# 其他

**Comment by DoctorReid** [comment]
地图放大可以考虑。

模拟按钮很难兼容秘技开怪，目前还在想替代方案。不过近期应该先搞第九宇宙
