### ISSUE TITLE
无法加载开拓力界面

### ISSUE THREAD

**Issue by ousogen** [DoctorReid/StarRailOneDragon#248]
# 使用版本

版本 `1.1.4`

# 问题应用

- `开拓力`

# 问题分类

- `运行失败` - 无法进行挑战、挑战后无法继续运行等。

# 问题描述

在更新版本1.1.4之后
点击开拓力界面，但是界面没有变化。无法编辑开拓力计划。
同样的问题在历战余响和逐光捡金界面也在发生。
换回以前的版本也会发生同样的问题

<img width="767" alt="スクリーンショット 2024-03-29 104238" src="https://github.com/DoctorReid/StarRailOneDragon/assets/135966343/d6d9fd86-791a-461d-88dd-3d5f3d4af37a">

使用的是.exe

**Comment by DoctorReid** [comment]
我没问题，需要日志

**Comment by ousogen** [comment]
删除文件夹再重新下载之后可以打开了，谢谢帮助
