### ISSUE TITLE
能否在模拟宇宙导航栏中，增加“运行”界面

### ISSUE THREAD

**Issue by vvincee7** [DoctorReid/StarRailOneDragon#250]
# 问题描述

就像在锄大地栏目中，有“运行”“绘制路线””特定路线名单“
希望在模拟宇宙栏目中，也增加”运行“
![image](https://github.com/DoctorReid/StarRailOneDragon/assets/161065827/3a03bbce-f303-4c99-88dd-ea9526e36c96)
![image](https://github.com/DoctorReid/StarRailOneDragon/assets/161065827/299131de-abb6-4c93-a905-4b9967e47910)

**Comment by DoctorReid** [comment]
优先级不高，后续考虑
