### ISSUE TITLE
GUI卡死问题

### ISSUE THREAD

**Issue by mal7hael** [DoctorReid/StarRailOneDragon#252]
# 使用版本

7849fb4 源码运行，1.2集成版本也存在此问题。

# 问题描述

脚本运行一段时间后GUI会卡死，表现为按钮无反应，但脚本仍可正常运行。
此时操作GUI的状态见视频：
https://github.com/DoctorReid/StarRailOneDragon/assets/23077424/86d4e115-a425-4e54-8d9c-d439357205ff

锄地任务完成时的屏幕截图：
![QQ截图20240331163927](https://github.com/DoctorReid/StarRailOneDragon/assets/23077424/b76fc213-1a13-45ec-bb10-d2d7bab44329)
可以看到，锄地已经完成了预定路线，但GUI中日志卡在大矿区就不再更新。

log正常记录，且未见错误。
[log.txt](https://github.com/DoctorReid/StarRailOneDragon/files/14814705/log.txt)

**Comment by DoctorReid** [comment]
目前确定 flet 版本 0.20.2 和 0.21.2 都会触发，暂时不知道原因

**Comment by vvincee7** [comment]
v1.2.4也出现了这个情况，gui卡死，但脚本还在继续运行

**Comment by DoctorReid** [comment]
2.2.1 仍然出现该问题
