### ISSUE TITLE
流光忆庭花火无法使用秘技

### ISSUE THREAD

**Issue by thunder12341** [DoctorReid/StarRailOneDragon#253]
# 使用版本
1.2.0

# 问题描述

![微信图片_20240331232141](https://github.com/DoctorReid/StarRailOneDragon/assets/142780230/d21f40fc-8ae9-4892-ace9-80b5fc61799f)
流光忆庭量子队进入战斗后换人花火，花火无法使用秘技并且直接报错结束进程

**Comment by DoctorReid** [comment]
其他角色会有问题吗

**Comment by thunder12341** [comment]
更新完又试了一下自动配队上半是停云 驭空 饮月 娜塔莎 都没开出来
