### ISSUE TITLE
支持每日购买气态流体和种子

### ISSUE THREAD

**Issue by yxjiang1125** [DoctorReid/StarRailOneDragon#256]
# 使用版本
1.2.1
# 问题描述
感谢作者大大开发一条龙！由于现在日常用黄泉锄大地，希望一条龙可以支持每天去仙舟买固定数量的气态流体和种子，用来合成奇巧零食，感谢！

**Comment by DoctorReid** [comment]
计划内 #245

**Comment by yxjiang1125** [comment]
非常感谢！！
