### ISSUE TITLE
多账号挂机切换问题建议

### ISSUE THREAD

**Issue by HxdRrkJglSUC** [DoctorReid/StarRailOneDragon#257]
# 使用版本

1.2.1

# 问题设置

设置-基础

# 问题描述

1、执行多账号挂机时，A脚本（官服）4:00启动，执行完毕后关闭游戏，B脚本（官服）8：00启动，不切换账号直接继续执行导致二次执行，B账号未挂机；执行完毕后关闭游戏，C脚本（亚服）12：00启动，未切换游戏版本继续执行导致进入官服，再次执行A脚本挂A账号。

ABC(DE)账号和对应客户端均已设置完毕，且在“设置-基础-多账号”内点击“登陆”，可以正常切换账号。

建议：多账号使用时，在开始执行脚本前，进行“关闭游戏-启动游戏-登出-输入账号密码-登入”达到切换账号的目的。

==更新：这个问题似乎并不是总是出现的，正常几次，出问题几次==

2、手动启动脚本时，A脚本执行完毕后，多账号会自动继续执行B、C脚本，尽管还没有到B、C的定时启动时间，不知道能不能使即使手动启动某个脚本，其他脚本依旧根据设定的时间启动

暂无合适的图片、日志可以提供

**Comment by DoctorReid** [comment]
这个场景有点复杂。ABC脚本是指开了多个脚本程序么，还是一个脚本程序里面设置了多个账号

**Comment by HxdRrkJglSUC** [comment]
一个程序里面设置的多账号：ABC为国服的三个账号，DE为亚服的两个账号，启动也只启动一个脚本程序。

问题1目前看来是没法切换程序，ABC执行完了还是在用国服登录DE，反之亦然；
↑这个问题有点说不清，等周末有空总结一下再组织一下语言和截图、日志啥的

问题2总是发生，不管设定的启动时间，只要手动启动了一个脚本，就会把所有的账号都跑一遍
↑这个问题基本是这样

**Comment by DoctorReid** [comment]
大概理解了。目前的确是支持不了你的场景。

1. 多账号下没有考虑中途关掉游戏重新开始
2. 一个脚本下无法定时两个时间分别两套账号的一条龙

**Comment by HxdRrkJglSUC** [comment]
好的，谢谢大佬，期待能拨冗改进
