### ISSUE TITLE
Anyway to translate the app to english?

### ISSUE THREAD

**Issue by wyvernstar** [DoctorReid/StarRailOneDragon#260]
Hello sir, i found this script very interesting but i cannot use this script since is only in chinese, if there a way to translate let me know

**Comment by DoctorReid** [comment]
If you know about coding, you can help with English localization

**Comment by wyvernstar** [comment]
> If you know about coding, you can help with English localization

hmmm sadly idk anything about coding

**Comment by DoctorReid** [comment]
A long time ago, English was supported. And there is a language setting in the script.

But no one used it,  so some further development is not compatible with English. And now only part of ui can be translated to English.

You can give it a try. But I am not sure whether it can work well.

Use some screenshot tool to capture ui and do translation. The settings is in [设置] - [游戏]
