### ISSUE TITLE
软件无法正常关闭

### ISSUE THREAD

**Issue by luoye321** [DoctorReid/StarRailOneDragon#264]
# 使用版本

填写使用的脚本版本，例如 `1.2.4`

# 问题应用

填写一个出现问题的应用，未出现的应用可移步至对应的模板 (保留一个即可)

`, 其他`

# 问题描述

请尽量描述发生问题的上下文。最好提供截图。

大佬  脚本一直显示运行中无法关闭 也没法点击暂停和结束 只能去任务管理器结束软件才可以 

另外，可以将 `.log/log.txt` 上传。

**Comment by DoctorReid** [comment]
同 #252
