### ISSUE TITLE
能否支援智識命途

### ISSUE THREAD

**Issue by bookbug666** [DoctorReid/StarRailOneDragon#267]
# 使用版本

`1.2.4`

# 问题描述

能否支援`智識`命途
![image](https://github.com/DoctorReid/StarRailOneDragon/assets/29662367/19df75e0-c0ab-4818-8d7c-e1f114b6979c)

**Comment by DoctorReid** [comment]
目前应该是支持的，只是被你最后一份【存护】的配置占了位置。

解决方案 【模拟宇宙】-【挑战配置】：
1. 如果能删掉最后一份存护的配置，就删掉，然后应该就有一份默认的【智识】命途配置。
2. 如果不想删掉，就自己新建一份，然后选择【智识】命途，和其它对应的配置。

**Comment by bookbug666** [comment]
感謝，解決了
