### ISSUE TITLE
锄大地过程中的部分漏怪

### ISSUE THREAD

**Issue by vvincee7** [DoctorReid/StarRailOneDragon#272]
# 使用版本

1.3.0

# 问题分类

- `漏怪`

# 路线名称

仙舟-麟渊境-宫墟深处
角色在执行时会因为卡脚而无法顺利击碎台阶下的秘技罐，导致路线执行失败

![image](https://github.com/DoctorReid/StarRailOneDragon/assets/161065827/04746442-484b-4473-964c-b29a8c4f49d4)
![image](https://github.com/DoctorReid/StarRailOneDragon/assets/161065827/13e9ef75-1318-479d-a473-c66783ffd494)

匹诺康尼-筑梦边境-回忆金花
会漏一只怪（我感知是百分百漏怪）

![image](https://github.com/DoctorReid/StarRailOneDragon/assets/161065827/e6f42a17-3f56-40db-9f9e-851b59430e56)
![image](https://github.com/DoctorReid/StarRailOneDragon/assets/161065827/f0ec9222-c4cf-45a2-a716-af30fd5d0280)

匹诺康尼-稚子的梦-回忆走廊
右上角房间里会漏一只怪（有概率发生）

![image](https://github.com/DoctorReid/StarRailOneDragon/assets/161065827/1c5fd31f-da4e-4553-bf08-2f92c7642c31)
![image](https://github.com/DoctorReid/StarRailOneDragon/assets/161065827/92c8c293-2062-40af-93ed-d06b9074fa4b)

雅利洛-城郊雪原-花
整条路线靠后的左右两侧的两拨怪，经常在此处进入战斗，而不是黄泉直接e掉，也发生过漏怪的情况

![image](https://github.com/DoctorReid/StarRailOneDragon/assets/161065827/64c97f5d-bc0d-4087-b93a-e52bdbf139b2)
![image](https://github.com/DoctorReid/StarRailOneDragon/assets/161065827/4cdefe09-13e2-45c7-bc07-1254ee0b395e)

以上

**Comment by DoctorReid** [comment]
脚本有路线编辑器，可以试试自己改路线之后提交

**Comment by DoctorReid** [comment]
目前一个点里有>=3个怪的时候，就有可能A掉2个然后跑去下一个点，这个在之后改用yolo检测攻击图标能有改善

**Comment by vvincee7** [comment]
> 脚本有路线编辑器，可以试试自己改路线之后提交

尝试了一下，没搞明白咋用，是需要直接在地图上进行标点进行移动吗？但是地图太小了完全看不清楚标的点

**Comment by DoctorReid** [comment]
文档wiki有写，可以多试试
