### ISSUE TITLE
匹诺康尼部分地图识别有误

### ISSUE THREAD

**Issue by um1ir0** [DoctorReid/StarRailOneDragon#280]
# 使用版本

1.3.0

# 问题分类

卡死

# 路线名称

匹诺康尼_筑梦边境
匹诺康尼_稚子的梦

# 问题描述

地图无法自动拖动至家族建设局的传送点位面 看了半天文件没找到识别地图传送点相关的文件
尝试了各个传送点发现是地图识别问题 不会移动地图位置

# 其他

cpu_count: 16
cpu_frequency: 2496.0MHz
memory_total: 31.705963134765625 GB
memory_used: 6.999843597412109 GB

[log.txt](https://github.com/DoctorReid/StarRailOneDragon/files/15272561/log.txt)
![无标题](https://github.com/DoctorReid/StarRailOneDragon/assets/91150523/c231b163-7183-43c7-ad4b-e41f1ba0c89c)

**Comment by DoctorReid** [comment]
大概率是地图上未完成的图标导致的

**Comment by DoctorReid** [comment]
尝试关闭任务追踪
