### ISSUE TITLE
白日梦酒店梦境部分路线绘制有误

### ISSUE THREAD

**Issue by PourJustice** [DoctorReid/StarRailOneDragon#286]
# 使用版本
2.2.1
# 问题分类
- `卡死` 
# 路线名称
匹诺康尼_白日梦酒店梦境_贵宾休息室走廊`路线绘制有误

![{663058E0-58FD-4686-A455-94A4EFC261A6}](https://github.com/DoctorReid/StarRailOneDragon/assets/160811962/580cc947-16ec-4b53-93bd-6f294dd7df1a)

以及
匹诺康尼_白日梦酒店梦境_贵宾休息室走廊02`路线绘制有误
![QQ截图20240514002745](https://github.com/DoctorReid/StarRailOneDragon/assets/160811962/5f1b003f-83fb-4bcd-9f3f-8c8d71c66ba7)

**Comment by DoctorReid** [comment]
可能是你的大地图文件或者路线文件没有更新，是不是下载整个新的压缩包运行的？

**Comment by PourJustice** [comment]
已解决，感谢
