### ISSUE TITLE
进入下层时卡住不动

### ISSUE THREAD

**Issue by Whiked** [DoctorReid/StarRailOneDragon#287]
# 使用版本

2.2.0

# 问题分类

选择问题对应的分类 (保留一行即可)

- `卡死` - 通常日志中失败原因为 `无法识别坐标`，或日志循环

# 问题宇宙

选择遇到问题的宇宙 (保留一行即可)

- `第六宇宙`

# 问题楼层

选择遇到问题的楼层 (保留一行即可)

每个

# 路线名称

每一条

# 问题描述

该层怪打完后，在移动到下一层时，无法触发移动指令
人工干预移动到下一层后，脚本可以继续运行，但是打完该层需要向下一层移动时还会卡住，如图，挂上机就睡觉然后我睡了多长时间角色在副本站了多长时间（）
![8b956e5d055141598188722327dceb28](https://github.com/DoctorReid/StarRailOneDragon/assets/100104340/acab33de-9a4f-4ea6-a8b8-3bd84f822d43)
![1c6ffa537feb3a0f6a49ba3ddfbfbdee](https://github.com/DoctorReid/StarRailOneDragon/assets/100104340/24620dc8-3a15-43e1-ab5f-aaadb3f1f20a)

**Comment by Whiked** [comment]
刚看到新版本 不好意思

**Comment by Whiked** [comment]
新版本也会卡住
![632d1ccf3d6e57cbe72f72651ba29809](https://github.com/DoctorReid/StarRailOneDragon/assets/100104340/c86a2f47-92b6-48fa-bee8-8a58e9f866d9)

**Comment by DoctorReid** [comment]
@Whiked 我试了下并不会卡住，你是重新下载的完整压缩包吗

**Comment by Whiked** [comment]
@DoctorReid 我是在软件内点更新直接更新的（）刚刚试了下重新下载压缩包覆盖就没问题了
