### ISSUE TITLE
模拟宇宙智识命途不选智识祝福

### ISSUE THREAD

**Issue by vvincee7** [DoctorReid/StarRailOneDragon#288]
# 使用版本

2.2.1

# 问题分类

- `其他`

# 问题描述

智识命途不选智识祝福（盯着打的，出现了智识祝福但是没选

![image](https://github.com/DoctorReid/StarRailOneDragon/assets/161065827/99d41465-e5dc-452a-b3da-caa2c35148e3)

![image](https://github.com/DoctorReid/StarRailOneDragon/assets/161065827/01858bab-0d0b-40ce-8e38-46098caf18af)

**Comment by DoctorReid** [comment]
模拟宇宙-挑战设置。看看智识的配置里填了什么祝福

**Comment by vvincee7** [comment]
![image](https://github.com/DoctorReid/StarRailOneDragon/assets/161065827/382927a5-1c16-4c48-b58f-9effe5f55c94)

**Comment by DoctorReid** [comment]
的确是漏了，你可以在右侧 命途选择智识，然后勾选第一个 智识

这个选项在最后代表，没有出现前面的祝福时，随便选一个智识祝福兜底
