### ISSUE TITLE
第四模拟宇宙打完精英怪不会领奖励

### ISSUE THREAD

**Issue by yamadafz** [DoctorReid/StarRailOneDragon#289]
# 使用版本
2.2.1
填写使用的脚本版本，例如 `1.0.0`

# 问题应用

填写一个出现问题的应用 (保留一行即可)

- `模拟宇宙`

# 问题分类

选择问题对应的分类 (保留一行即可)

- `运行失败` - 无法进行挑战、挑战后无法继续运行等。

# 问题描述
第四模拟宇宙打完精英怪不会领奖励自动下一层，设置找遍了也没有相关设置
请尽量描述发生问题的上下文。最好提供截图。

例如，历战回响战斗胜利后，在领取奖励画面卡死。

另外，可以将 `.log/log.txt` 上传。

**Comment by DoctorReid** [comment]
开拓力，选模拟宇宙
