### ISSUE TITLE
模拟宇宙休整层，攻击罐子失败

### ISSUE THREAD

**Issue by vvincee7** [DoctorReid/StarRailOneDragon#296]
# 使用版本

2.2.1

# 问题分类

- `其他`

# 问题宇宙

- `第三宇宙`

# 问题楼层

- `区域 - 休整`

# 问题描述

在进入休整层后直接进行普攻，黄泉作为一号位打不到右侧的罐子，建议向右侧走两步再进行普通攻击

还有就是想请问一下精英层的逻辑，我使用黄泉砂金花火佩拉配队（1234号位顺序），在精英和boss，切换到了砂金秘技然后普攻开怪，这是啥情况啊

**Comment by DoctorReid** [comment]
战技点不足时，精英层目前是优先上buff，最后还没有做一个攻击角色的切换

**Comment by DoctorReid** [comment]
#294 旧宇宙的休整层还没有用新的逻辑
