### ISSUE TITLE
YOLO模型下载失败

### ISSUE THREAD

**Issue by atiasn** [DoctorReid/StarRailOneDragon#309]
# 使用版本

填写使用的脚本版本：2.2.2

# 问题描述

YOLO模型下载失败
![image](https://github.com/DoctorReid/StarRailOneDragon/assets/25135479/a6ed34ad-a946-4564-ad71-e02164d93e3e)

日志：
[log.txt](https://github.com/DoctorReid/StarRailOneDragon/files/15378239/log.txt)

**Comment by DoctorReid** [comment]
脚本默认的值写错了，手动选一下 `yolov8n-640-simuni-0512` 就好
