### ISSUE TITLE
锄大地可以在第一遍之后再开始一次么

### ISSUE THREAD

**Issue by Sincerely-lk** [DoctorReid/StarRailOneDragon#310]
# 使用版本
2.2.1

# 问题分类
添加功能

# 问题描述
   锄大地有时候会失败导致该路线后面的怪没有清理，在锄大地走完后 再点击开始会发现每个地图都有记录是否清理完成，没有的图会再次重新去清理一下，希望能添加到功能里，在第一遍清图之后自动重新检查一次（大概就是再点一次开始按钮在检测一遍，有漏怪接着清一下）， 辛苦作者。

# 其他

**Comment by DoctorReid** [comment]
目前没有漏怪检测，只能失败的路线重试一次

**Comment by Sincerely-lk** [comment]
> 目前没有漏怪检测，只能失败的路线重试一次

那么可以在一遍完成后自动进行第二次么？
