### ISSUE TITLE
UI界面右上角角色详情有红点 无法正确执行 返回普通大世界

### ISSUE THREAD

**Issue by ShinaKaria** [DoctorReid/StarRailOneDragon#316]
# 使用版本

2.2.2

# 问题应用

开拓力，但应该不是光开拓力有这个问题

# 问题描述

当角色有星魂未激活时，UI界面右上角角色详情有红点 无法正确执行 返回普通大世界

逐个清理红点后 当右上角角色详情没有红点时 正常执行

![image](https://github.com/DoctorReid/StarRailOneDragon/assets/87139540/f5027668-5d84-4113-b29b-af4654970197)

**Comment by DoctorReid** [comment]
wiki有说明，需自行清理红点

**Comment by ShinaKaria** [comment]
> wiki有说明，需自行清理红点

了解 没注意看
