### ISSUE TITLE
钟表匠遗器副本 无法匹配大地图

### ISSUE THREAD

**Issue by ShinaKaria** [DoctorReid/StarRailOneDragon#317]
# 使用版本

2.2.2

# 问题应用

- `开拓力`

# 问题分类

选择问题对应的分类 (保留一行即可)

- `运行失败` - 无法进行挑战、挑战后无法继续运行等。

# 问题描述

钟表匠遗器副本 无法匹配大地图 额外测试了 大公、速度套、猎人 三个都正常 

![image](https://github.com/DoctorReid/StarRailOneDragon/assets/87139540/9386a194-6073-4d26-a14b-0e8761d2956a)

**Comment by DoctorReid** [comment]
wiki都有写
脚本是按完成所有游戏内容后的状态进行编写的，以下情况有几率导致脚本出错：
- 右上角的角色图标有红点
- 游戏内开启了任务追踪
- 大地图未完全开启
- 大地图上有通关后图标会消失的内容 （即你未通关，有多余的图标）

**Comment by hanuxxx** [comment]
我也有同样的问题，检查了地图没有多余的图标了

**Comment by ShinaKaria** [comment]
> wiki都有写 脚本是按完成所有游戏内容后的状态进行编写的，以下情况有几率导致脚本出错：
> 
> * 右上角的角色图标有红点
> * 游戏内开启了任务追踪
> * 大地图未完全开启
> * 大地图上有通关后图标会消失的内容 （即你未通关，有多余的图标）

@DoctorReid 右上角无红点 游戏开任务追踪 大地图已开启 能够正常进入到大地图 并拖拽 并且肉眼能看看到副本图标 但是无法匹配

**Comment by hanuxxx** [comment]
> wiki都有写 脚本是按完成所有游戏内容后的状态进行编写的，以下情况有几率导致脚本出错：
> 
> * 右上角的角色图标有红点
> * 游戏内开启了任务追踪
> * 大地图未完全开启
> * 大地图上有通关后图标会消失的内容 （即你未通关，有多余的图标）

检查了程序里的地图图片和游戏画面，发现游戏画面的图标每个都比图片稍微大一点，其他地方肉眼看着都一样，可能是这个原因，不知道是不是个例

**Comment by DoctorReid** [comment]
周末只顾着写代码了。

这么神奇，大地图是用最小缩放比例么？游戏分辨率和屏幕分辨率多少

方便的话就用脚本的F11截图给我看看

**Comment by ShinaKaria** [comment]
> 周末只顾着写代码了。
> 
> 这么神奇，大地图是用最小缩放比例么？游戏分辨率和屏幕分辨率多少
> 
> 方便的话就用脚本的F11截图给我看看

大地图最小比例 分辨率和屏幕都是1920*1080

但是，我找到了可能出现的问题

我重新用源代码跑了一遍 能够正常识别副本

我又下载了2.2.2的release 也能够正常识别

但是原先通过update升上来的2.2.2却不能识别

这可能是update带来的问题

**Comment by ShinaKaria** [comment]
在设置界面能够看到 通过update更新上来的脚本 应该是旧版本的ui 可能也有部分文件/资源 更新失败
![image](https://github.com/DoctorReid/StarRailOneDragon/assets/87139540/c0c93d22-a8dd-4497-b7b6-989d404ac343)

**Comment by ShinaKaria** [comment]
另外 发现的问题是 
release版本的F11无法截图(新下载的版本 非更新上来的版本)
源代码的F11截图正常

**Comment by DoctorReid** [comment]
应该就是脚本更新的问题了，这个玩意我还不确定为什么会丢文件

#321

**Comment by DoctorReid** [comment]
知道原因了 大概是复制文件的时候没法覆盖被exe读取锁定的文件，后续修复
