### ISSUE TITLE
v2.2.2更新失败

### ISSUE THREAD

**Issue by MyAngelKokkoro** [DoctorReid/StarRailOneDragon#322]
# 使用版本
2.2.2

# 问题描述
在脚本内检查更新时下载失败
请尽量描述发生问题的上下文。最好提供截图。

![QQ截图20240527205410](https://github.com/DoctorReid/StarRailOneDragon/assets/166719271/d12e069d-0a6d-4a10-9259-02de1ac3ddd3)

**Comment by ShinaKaria** [comment]
去掉v  2.2.2没有v

**Comment by DoctorReid** [comment]
暂时不要用这个功能哈 等待修复 #321
