### ISSUE TITLE
[问题反馈] 对b服的支持

### ISSUE THREAD

**Issue by Dekirumonka** [DoctorReid/StarRailOneDragon#326]
### 使用版本

2.2.3

### 问题描述

b服开始运行的时候无法正确运行
首先是在登陆器界面就无法点击开始游戏按钮
进入游戏后也无法点击登录按钮，导致后续无法进行

### 游戏截图

![_1717472722156](https://github.com/DoctorReid/StarRailOneDragon/assets/17879091/2fb535be-f3b5-4613-a12b-07e0b64bbbaf)

### 运行日志

[log.txt](https://github.com/user-attachments/files/15542235/log.txt)

### 你的建议

添加针对B服的识别，

**Comment by DoctorReid** [comment]
这是启动器，不是游戏本体吧

**Comment by Dekirumonka** [comment]
游戏路径设为游戏本体的话，进入游戏后显示的是官服的登录界面，不是b服的登录界面，无法正常登录
![Honkai  Star Rail Screenshot 2024 06 04 - 17 37 11 35](https://github.com/DoctorReid/StarRailOneDragon/assets/17879091/99fd4e90-40a5-4fb0-bc82-f7819b7f31c6)

**Comment by DoctorReid** [comment]
我的机子没有B服，我理解应该会有一个B服的游戏本体exe的。

你可以用启动器启动游戏后，通过【任务管理器】，找到崩铁，然后右击，【打开文件所在位置】，看看是否有另一个exe

**Comment by Dekirumonka** [comment]
> 我的机子没有B服，我理解应该会有一个B服的游戏本体exe的。
> 
> 你可以用启动器启动游戏后，通过【任务管理器】，找到崩铁，然后右击，【打开文件所在位置】，看看是否有另一个exe

没有的，B服是通过启动器打开的，游戏本体使用的是同一个exe，用启动器进去就是b服，从外部程序打开会导致变成官服。
b站有通过插件把官服修改为b服启动的方法，供参考：https://www.bilibili.com/video/BV1fw4m1m7AF/

**Comment by DoctorReid** [comment]
现在米哈游有自己一个统一的启动器，B服启动器的界面跟这个一样吗

**Comment by Dekirumonka** [comment]
> 现在米哈游有自己一个统一的启动器，B服启动器的界面跟这个一样吗

基本是一样的但是无法切换到别的游戏
![VZ6LAAYA0S$7B5ECB72C9SJ](https://github.com/DoctorReid/StarRailOneDragon/assets/17879091/6fb8448c-d854-4e06-9247-99af92c96968)
另外新版的官服和b服启动器的切换也有人做了 https://www.bilibili.com/video/BV1eSViepE2R/
