### ISSUE TITLE
[问题反馈] 使用锄大地功能的时候运行久了会电脑重启

### ISSUE THREAD

**Issue by SunShawChuan258** [DoctorReid/StarRailOneDragon#332]
### 使用版本

2.2.3

### 问题分类

其它

### 问题描述

总共使用过两次锄大地功能，两次都打着打着电脑重启，使用的是默认路线，第一次运行的时候打到仙舟电脑就重启了，第二次的时候则是在黑塔空间站就重启了，日志大概在[14:28:44.233]这个位置
---------
还有一个问题，勾选了每日实训功能，但是没有收取每日委托的那些经验

### 游戏截图

![bug](https://github.com/DoctorReid/StarRailOneDragon/assets/172246235/01b12771-ceb7-401c-9292-d0dd6e5f3f32)

### 运行日志

[log.txt](https://github.com/user-attachments/files/15757585/log.txt)

**Comment by DoctorReid** [comment]
会不会是电脑散热问题导致的重启，脚本的运算的确都是依赖cpu的

**Comment by SunShawChuan258** [comment]
> 会不会是电脑散热问题导致的重启，脚本的运算的确都是依赖CPU的

不是的，我今天从头到尾录制了一遍一条龙的视频
![image](https://github.com/DoctorReid/StarRailOneDragon/assets/172246235/19482524-c9a7-48e7-bc7d-1cca540d9377)
录制视频1小时14分48秒然后蓝屏，电脑重启，用aida64和Intel的监控，看到这个时候cpu并不热，显卡也是正常温度，我的电脑单烤fpu一小时20分钟cpu温度也就71
![4 2-1 0562](https://github.com/DoctorReid/StarRailOneDragon/assets/172246235/1e71aac1-b863-4473-85dd-0a324609e42f)

**Comment by SunShawChuan258** [comment]
[log.txt](https://github.com/user-attachments/files/15782440/log.txt)
附上今日日志

**Comment by DoctorReid** [comment]
好神奇。重启之前脚本在干什么

**Comment by DoctorReid** [comment]
目前还没有收到其它反馈重启的情况

**Comment by SunShawChuan258** [comment]
> 好神奇。重启之前脚本在干什么

我看到就是在仙舟点了个传送之后就蓝屏了，然后重启，上面发的那个截图就是蓝屏前录的最后一秒

**Comment by SunShawChuan258** [comment]
> 目前还没有收到其它反馈重启的情况

大佬，今天尝试用了下设置黄泉仅秘技开怪，然后刚打完一只怪就蓝屏一次，我以为可能是运行时间长了然后会让我电脑蓝屏，但是我重启之后再单跑一遍锄大地，打了两只怪又蓝屏重启了

**Comment by DoctorReid** [comment]
蓝屏显示的代码是啥，只能从这个开始查了

**Comment by SunShawChuan258** [comment]
会不会是硬件问题？我的CPU是5600x，显卡是英特尔的a750，系统是win10  22h2

**Comment by SunShawChuan258** [comment]
蓝屏闪的太快了，我晚上有空了再抓拍一下吧

**Comment by DoctorReid** [comment]
我对硬件也不是很了解。只能用蓝屏代码去搜问题或者问问gpt

另外搜了下，windows蓝屏后是有dump文件的，然后可以提交的微软的官网，会有人帮忙分析下是什么问题。

[例子](https://answers.microsoft.com/zh-hans/windows/forum/all/windows-%E8%93%9D%E5%B1%8F-full-dump/5b3dcee1-0e00-4734-ae88-ee5b49a4e6bf)

到时候看看是什么冲突导致的

**Comment by SunShawChuan258** [comment]
我电脑最后一次生成dump文件是五月份，刚刚蓝屏都没有生成dump文件，不过我在windows日志里面找到了这几个报错的事件，每一次蓝屏之后都是这四个轮流报错
[6-12事件41.txt](https://github.com/user-attachments/files/15797903/6-12.41.txt)
[6-12事件161.txt](https://github.com/user-attachments/files/15797904/6-12.161.txt)
[6-12事件7001.txt](https://github.com/user-attachments/files/15797905/6-12.7001.txt)
[6-12事件7023.txt](https://github.com/user-attachments/files/15797906/6-12.7023.txt)

**Comment by SunShawChuan258** [comment]
![image](https://github.com/DoctorReid/StarRailOneDragon/assets/172246235/82dbdf4a-fecc-4987-a0f7-5d8607eb5a37)
截到了，真就只出来一瞬间，开0.2倍速才截到

**Comment by SunShawChuan258** [comment]
WHEA_UNCORRECTABLE_ERROR

**Comment by DoctorReid** [comment]
的确看不懂，以下是GPT回复。

```txt
WHEA_UNCORRECTABLE_ERROR 是 Windows 的蓝屏死机（BSOD）错误，表明存在硬件故障。以下是一些排查步骤：

检查硬件：确保所有硬件组件连接正常。
更新驱动程序：确保所有驱动程序都是最新的。
运行诊断工具：使用内置工具检查硬件完整性（例如，内存诊断）。
检查过热情况：确保系统不过热。
更新 BIOS/UEFI：确保 BIOS/UEFI 是最新的。
运行 SFC/Scannow：使用系统文件检查器修复损坏的文件。
```

另外我看上面4个txt有两个是跟虚拟机相关的，如果不使用的话可以尝试卸载，或者禁用相关服务，参考 [链接](https://www.fujieace.com/vmware/usb-arbitration-service.html) 。

目前看不出啥，我建议是到微软官网寻求帮助，先分析dump看是哪个服务引起的蓝屏，才有可能知道是脚本里使用的哪个库导致的问题。

**Comment by SunShawChuan258** [comment]
> 的确看不懂，以下是GPT回复。
> 
> ```
> WHEA_UNCORRECTABLE_ERROR 是 Windows 的蓝屏死机（BSOD）错误，表明存在硬件故障。以下是一些排查步骤：
> 
> 检查硬件：确保所有硬件组件连接正常。
> 更新驱动程序：确保所有驱动程序都是最新的。
> 运行诊断工具：使用内置工具检查硬件完整性（例如，内存诊断）。
> 检查过热情况：确保系统不过热。
> 更新 BIOS/UEFI：确保 BIOS/UEFI 是最新的。
> 运行 SFC/Scannow：使用系统文件检查器修复损坏的文件。
> ```
> 
> 另外我看上面4个txt有两个是跟虚拟机相关的，如果不使用的话可以尝试卸载，或者禁用相关服务，参考 [链接](https://www.fujieace.com/vmware/usb-arbitration-service.html) 。
> 
> 目前看不出啥，我建议是到微软官网寻求帮助，先分析dump看是哪个服务引起的蓝屏，才有可能知道是脚本里使用的哪个库导致的问题。

大佬，可能找到原因了，我查资料把BIOS里面的C-State关掉，然后我再跑了一遍锄大地，现在已经打完全部怪，自动结束脚本了

**Comment by DoctorReid** [comment]
good

**Comment by SunShawChuan258** [comment]
大佬，今天又跑了一次一条龙，打到仙舟又重启了，貌似每次蓝屏重启都是在迴星港，过了迴星港就好了

**Comment by DoctorReid** [comment]
之前忘记回复了。。就把有问题的路线加到黑名单不去跑吧
