### ISSUE TITLE
[问题反馈] [模拟宇宙] 选择祝福时卡死，无限重置

### ISSUE THREAD

**Issue by ghjcfrt** [DoctorReid/StarRailOneDragon#333]
### 使用版本

2.2.3

### 问题宇宙

第九宇宙

### 问题区域

全部区域

### 问题描述

我不确定是否仅存在于第九宇宙，但其他宇宙没有测试，目前先写第九宇宙。
在选择祝福界面，如果重置次数耗尽后，没有合适的祝福选择会再一次进行重置，陷入无尽重复，随后进入结束并结算指令，无限重复，卡死。

### 游戏截图

![image](https://github.com/DoctorReid/StarRailOneDragon/assets/73391769/5b8d915b-40cf-4c46-b555-a0d9d68a8af7)

### 运行日志

[log.txt](https://github.com/user-attachments/files/15764764/log.txt)

### 你的建议

重置一定次数后随机选择或默认第一个
或者加入检测剩余重置次数

**Comment by DoctorReid** [comment]
大概率开了什么滤镜，重置祝福不能使用的时候应该是红色的
