### ISSUE TITLE
[问题反馈] 增加跨日月卡识别

### ISSUE THREAD

**Issue by MyAngelKokkoro** [DoctorReid/StarRailOneDragon#334]
### 使用版本

v2.2.3

### 问题描述

1.运行模拟宇宙
2.跨日遇到月卡界面卡死

### 游戏截图

无

### 运行日志

[log.txt](https://github.com/user-attachments/files/15782055/log.txt)

### 你的建议

加入一个时间识别，快到月卡刷新的时间时暂停当前运行，然后准备点月卡

**Comment by DoctorReid** [comment]
模拟宇宙目前在战斗楼层的移动是有识别月卡的，其它的情况比较多，考虑统一在运行失败时候处理月卡，[模拟宇宙 结束并结算]
