### ISSUE TITLE
[问题反馈] [模拟宇宙] 模拟宇宙第二层报错退出

### ISSUE THREAD

**Issue by conanlp89** [DoctorReid/StarRailOneDragon#335]
### 使用版本

2.2.3

### 问题宇宙

全部宇宙

### 问题区域

全部区域

### 问题描述

进入第二层之后马上报错,游戏内退出模拟宇宙

### 游戏截图

![微信截图_20240613233324](https://github.com/DoctorReid/StarRailOneDragon/assets/41106895/7fb51b57-facf-4261-9a8e-df2a78e7a152)

### 运行日志

[log.txt](https://github.com/user-attachments/files/15823368/log.txt)

**Comment by DoctorReid** [comment]
应该是使用的角色刚好有bug，可能是同谐主和波提欧的问题，先使用其它配队，周末修复
