### ISSUE TITLE
脚本错误

### ISSUE THREAD

**Issue by qweasd36479** [DoctorReid/StarRailOneDragon#338]
![image](https://github.com/DoctorReid/StarRailOneDragon/assets/74939730/2e775abc-9df4-496e-a0cc-cd726870b9c5)
前一天还能用的 隔天打开就跳错误 重新装了numpy 还是跳了错误  该如何解决呢

**Comment by DoctorReid** [comment]
再试试新的 https://github.com/DoctorReid/StarRailOneDragon/releases/tag/2.2.4

**Comment by qweasd36479** [comment]
第一次开的时候跳了另一个错误  重开之后就好了 非常感谢
