### ISSUE TITLE
[需求建议] 大佬是否可以加入推送功能呢，比如Qmsg，pushplus这种

### ISSUE THREAD

**Issue by Clulu1499** [DoctorReid/StarRailOneDragon#343]
### 使用版本

2.2.3

### 当前状况

正常运行

### 你的建议

可否增加一条龙运行完毕后推送完成的消息

**Comment by DoctorReid** [comment]
按目前的计划，可能要比较久之后了，因为下个月想尝试一下做绝区零的脚本，到时候应该也会做这个功能，但优先级不高。

如果你懂代码开发，可以帮忙开发这块

**Comment by Clulu1499** [comment]
好吧，感谢大佬了——
