### ISSUE TITLE
[问题反馈] [模拟宇宙] 

### ISSUE THREAD

**Issue by nuomitan** [DoctorReid/StarRailOneDragon#346]
### 使用版本

2.2.2-2.3.0

### 问题宇宙

第四宇宙

### 问题区域

区域 - 战斗

### 问题描述

2.2.1之后黄泉秘技经常瞎砍怪往后砍，导致位置乱了，离地图上设定的出口远了，这经常会导致系统判定不到出口在哪，就会重开，这样前面的关卡都白打了，很不稳定。然后是官服更新2.3版本后应该是改动了一点，模拟宇宙新一轮一开始选择开拓祝福的时候，程序判定不到，就一直卡在那里。

### 你的建议

建议黄泉战斗方式改回2.2.1，这时候的黄泉放e会回调身位的，所以位置不会乱，反而稳定性是最好的，不会因为程序找不到路而重开，导致刷狗粮效率低下。另外经过我的测试第四宇宙黄泉队效率是最高的，建议围绕第四宇宙优化最好。最后，也感谢开发者的辛勤劳动开发的自动化神器，为广大玩家节省大量时间，提升游戏体验，祝开发者生活工作愉快，开开心心每一天。

**Comment by DoctorReid** [comment]
新逻辑也有反方向攻击的逻辑，移位应该是红色感叹号一直在某一边。

周末有空的话可以开个录屏，把移位特别严重的QQ发我看看。我有空也观察一下

**Comment by skycon8** [comment]
2.3后一直卡在开始选祝福那里。鼠标一直停在左下角落不做选择。

**Comment by nuomitan** [comment]
还有几个地图也是这样，印象中集中在前面几个关卡，后面的很少，应该是人物位移后离太远了，然后镜头转太快cpu没反应过来吧，如果出口离近点就不会出现这种情况。
其实可以设计成检查到红蓝色出口（门要一定距离才会完全打开，不打开的情况下，程序一定检测不到）就前走几步。
ps2.2.1版本很稳定，基本不会出错。




myis
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DoctorReid/StarRailOneDragon"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月21日(星期五) 下午4:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DoctorReid/StarRailOneDragon] [问题反馈] [模拟宇宙]  (Issue #346)





 
新逻辑也有反方向攻击的逻辑，移位应该是红色感叹号一直在某一边。
 
周末有空的话可以开个录屏，把移位特别严重的QQ发我看看。我有空也观察一下
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

录屏.rar (287.45M, 2024年07月22日 17:34 到期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=09356565d3f73cdac64dcc2a4039061b4c41045553090c00190c56565414000357024800000b501951025c00540800010d51075d663134f688f3a44b1458463409&t=exs_ftn_download&code=45eef944

**Comment by DoctorReid** [comment]
这个周末我自己测试下来还是挺正常的。

感觉应该跟画质有关系，发发画质设置看看。

后续会让yolo模型多训练点低画质的图片来提升一下。
