### ISSUE TITLE
[问题反馈] 每日特训奖励无法领取

### ISSUE THREAD

**Issue by PourJustice** [DoctorReid/StarRailOneDragon#348]
### 使用版本

2.3.0

### 问题描述

2.3版本更新后游戏对指南页签做了折叠，现在页签顺序跟以前不一样，脚本识别不出来

### 游戏截图

![Honkai  Star Rail Screenshot 2024 06 22 - 03 18 18 20](https://github.com/DoctorReid/StarRailOneDragon/assets/160811962/b5bf400d-e742-4930-936c-130f054ed897)

**Comment by DoctorReid** [comment]
2.3.2 修复了 等会试试
