### ISSUE TITLE
[问题反馈] 启动程序后，会在桌面创建空文件夹

### ISSUE THREAD

**Issue by ghjcfrt** [DoctorReid/StarRailOneDragon#349]
### 使用版本

2.3.0

### 问题描述

1.启动程序
2.桌面会出现空文件夹

具体为“Desktop\StarRailOneDragon\_internal\config\mystool2\data\nonebot-plugin-mystool”
程序并不保存在桌面 ，其在桌面创建的文件夹均为空文件夹（所有文件夹除了子文件夹外，无其他文件）
但删除后对程序并无影响

我是在大概三四个版本前开始使用的，这个问题一直存在。log中显示为“插件数据文件不存在”（因为最新的log中并无相关问题表述，所以我选取了存在相关表述的2024.06.07log文件）

### 运行日志

[log.txt](https://github.com/user-attachments/files/15935550/log.txt)

### 你的建议

更改数据文件保存位置

**Comment by DoctorReid** [comment]
这个是之前米游社签到插件的文件，后续会删掉。

把脚本放在其他目录应该就没有这个问题
