### ISSUE TITLE
[问题反馈] [模拟宇宙] 能否加个打过的精英数目的计数功能？每周最多100个精英掉材料，多的就浪费了

### ISSUE THREAD

**Issue by fateholder** [DoctorReid/StarRailOneDragon#356]
### 使用版本

2.2.2

### 问题宇宙

全部宇宙

### 问题区域

全部区域

### 问题描述

[问题反馈] [模拟宇宙] 能否加个打过的精英数目的计数功能？每周最多100个精英掉材料，多的就浪费了

**Comment by vvincee7** [comment]
![image](https://github.com/DoctorReid/StarRailOneDragon/assets/161065827/18f595fc-1ce8-4ca8-8260-c50adef2f63a)
这里不是会显示通关次数吗

**Comment by fateholder** [comment]
> ![image](https://private-user-images.githubusercontent.com/161065827/344425969-18f595fc-1ce8-4ca8-8260-c50adef2f63a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3MjIzNzAsIm5iZiI6MTcxOTcyMjA3MCwicGF0aCI6Ii8xNjEwNjU4MjcvMzQ0NDI1OTY5LTE4ZjU5NWZjLTFjZTgtNGNhOC04MjYwLWM1MGFkZWYyZjYzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQwNDM0MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YmYzNTJjMDBmMGI4ZmVjMzJkYzZhNTljYzE5ZTk0YjVkMDMxN2M1NTMxMTAyNzBlOTVmZTVlZGMwZmVhNDVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3dNiFjMU0PzF5Q8JKIKdgKWfRei-0_-e4Q_JjegxCjo) 这里不是会显示通关次数吗

大概有一半会在中途退出，，等到成功通关34次的时候，早超出100个精英个数了。

**Comment by DoctorReid** [comment]
后续更新一下，但优先级较低

**Comment by fateholder** [comment]
> 后续更新一下，但优先级较低

没事，不更新也行，我感觉有不少找不到路是因为出了商店找不到门导致的，只要都跳过商店，直奔下一层，可以减少不错跳出
