### ISSUE TITLE
[问题反馈] [锄大地] 地图识别和点击

### ISSUE THREAD

**Issue by Sincerely-lk** [DoctorReid/StarRailOneDragon#360]
### 使用版本

2.3.3

### 问题分类

卡死

### 问题描述

地图识别有问题，大地图一直往右滑不点击匹诺康尼，小地图，仙舟挺多地方点不进去，具体看下log，从最后网上看，我中间又校准一次也是一样。（2.3.2没这问题）

### 运行日志

[log.txt](https://github.com/user-attachments/files/16161946/log.txt)

**Comment by DoctorReid** [comment]
目前还没有其他人反馈类似问题，可以参考wiki看画面设置之类是否ok。

或者使用`F11`截图后上传

**Comment by Sincerely-lk** [comment]
> 目前还没有其他人反馈类似问题，可以参考wiki看画面设置之类是否ok。
> 
> 或者使用`F11`截图后上传

那我先用2.3.2吧，等下个版本再看看
