### ISSUE TITLE
[需求建议] 

### ISSUE THREAD

**Issue by qiling-online** [DoctorReid/StarRailOneDragon#364]
### 使用版本

2.3.3

### 当前状况

现在使用流萤作为一号位锄地，不会像黄泉一下在遇到怪之前开秘技，而是像阮梅一样战斗后开秘技，导致浪费

### 你的建议

流萤秘技的使用和黄泉的逻辑一样，在遇到怪尝试开启

**Comment by DoctorReid** [comment]
buff类不适合像黄泉一样，遇到怪才使用会被袭的
