### ISSUE TITLE
[问题反馈] [锄大地] 

### ISSUE THREAD

**Issue by Angelenx** [DoctorReid/StarRailOneDragon#370]
### 使用版本

2.4.0

### 问题分类

卡死

### 问题描述

锄大地正常运行，一段时间后UI卡死，不论点击什么也无反应，无法通过按钮停止脚本或者无法暂停脚本，日志也停止输出，但是锄大地依旧在正常运行，快捷键也生效，但是UI不刷新。

**Comment by DoctorReid** [comment]
这个问题存在很久了，一直不知道为什么

**Comment by Angelenx** [comment]
我一开始以为是爆显存了，但我调低画质情况也没有改善。
