### ISSUE TITLE
[问题反馈] [锄大地] 

### ISSUE THREAD

**Issue by Dekirumonka** [DoctorReid/StarRailOneDragon#371]
### 使用版本

2.3.3

### 问题分类

卡死

### 问题描述

场景：太卜司
表现：进入太卜司以后不动了，后续继续脚本从其他地方开始也无法继续识别区域状态

### 运行日志

[log2024-08-06.txt](https://github.com/user-attachments/files/16517007/log2024-08-06.txt)

**Comment by DoctorReid** [comment]
我没法重现，不知道现在还有没有这个问题
