### ISSUE TITLE
[问题反馈] [模拟宇宙] 黄泉第一层选祝福页面卡死

### ISSUE THREAD

**Issue by MyAngelKokkoro** [DoctorReid/StarRailOneDragon#382]
### 使用版本

2.4.0

### 问题宇宙

第七宇宙

### 问题区域

区域 - 战斗

### 问题描述

在第一层秘技砍完两个怪进选祝福页面的时候有可能会触发强制退出，此时会卡在选祝福页面，手动点击后会开始执行退出模拟宇宙。日志里大概是从三点半开始卡的

### 运行日志

[log.txt](https://github.com/user-attachments/files/16667897/log.txt)

**Comment by DoctorReid** [comment]
看日志不太能看出是什么触发的，应该是小概率事件，下次带上图片
