### ISSUE TITLE
[问题反馈] 

### ISSUE THREAD

**Issue by decblue** [DoctorReid/StarRailOneDragon#383]
### 使用版本

2.4.1

### 问题描述

运行任意功能会卡在加载ocr模型这一步

### 游戏截图

![Snipaste_2024-09-06_10-39-18](https://github.com/user-attachments/assets/faf1d5ab-5e68-43e2-bc17-6255c9bc40d2)

**Comment by vvincee7** [comment]
+1同样的问题

**Comment by DoctorReid** [comment]
有点重现不了，之前有人说重新解压新的就没问题了

配置文件的话，可以复制旧的config文件夹到新的里面，选择全覆盖就行
