### ISSUE TITLE
[问题反馈] 多个问题反馈

### ISSUE THREAD

**Issue by MyAngelKokkoro** [DoctorReid/StarRailOneDragon#385]
### 使用版本

2.4.1

### 问题描述

1.在一条龙界面设置定时启动+运行模拟宇宙会导致日志卡死，1ms刷新一条，导致日志文件巨大，且运行时间过长会导致程序卡死，需要用任务管理器关闭
2.米游社无法登录
3.定时启动无法设置，在定时启动选择时间后点击运行会直接启动而不是定时

### 游戏截图

![QQ截图20240913005156](https://github.com/user-attachments/assets/131d6f14-ef29-4678-bb6c-e6e268ce5e07)

### 运行日志

[log.txt](https://github.com/user-attachments/files/16983004/log.txt)

**Comment by DoctorReid** [comment]
新版本有新的定时方式了
