### ISSUE TITLE
[问题反馈] 

### ISSUE THREAD

**Issue by Rx-0Un** [DoctorReid/StarRailOneDragon#389]
### 使用版本

2.2.2

### 问题描述

EXE运行时要使用管理员方式运行不然系统会报错，建议在wiki或者PDF里标下

### 游戏截图

![image](https://github.com/user-attachments/assets/e2b69f88-8c28-4770-8eea-4711ffdfa6e2)

### 你的建议

建议在wiki或者PDF里标下

**Comment by DoctorReid** [comment]
一直都说明的

**Comment by Rx-0Un** [comment]
我在说明书和wiki上没看到，我有经验还好别的萌新看到说不定就不会用了，另外问一下如果我用别的Python脚本会不会有冲突

DoctorReid ***@***.***> 于2024年9月26日周四 09:26写道：

**Comment by devil233-ui** [comment]
> 一直都说明的

其实想问下不能做成和绝一样直接默认管理员运行么？还说是有什么顾虑
