### ISSUE TITLE
[问题反馈] [开拓力] 

### ISSUE THREAD

**Issue by wxdongg99** [DoctorReid/StarRailOneDragon#390]
### 使用版本

2.5.1

### 问题副本

霜风之径

### 问题描述

体力仅够刷一次时，刷完后会点击再来一次，导致返回大世界失败

### 游戏截图

![Snipaste_2024-10-06_23-00-25](https://github.com/user-attachments/assets/a2f2202c-091e-4a52-a0a2-6e036872e454)

### 运行日志

[log.txt](https://github.com/user-attachments/files/17269858/log.txt)

### 你的建议

1，判断弹出开拓力补充后返回至上一级，
2，再次执行返回大世界指令
3，判断是否回到大世界，失败后进入4 ，成功后继续原流程
4，按ESC并进入3,（循环N次后中断）

**Comment by DoctorReid** [comment]
新版本应该解决了
