### ISSUE TITLE
[需求建议] 增加分解4星仪器

### ISSUE THREAD

**Issue by Riceluo1996** [DoctorReid/StarRailOneDragon#392]
### 使用版本

通用

### 当前状况

增加懒度，可以设置一个额外的清理四星仪器的功能，这样不必因为背包满了进不去副本
如果可以的话，还可以把背包的仪器数量显示到脚本主页面

**Comment by DoctorReid** [comment]
先记着，项目在重构中，还要一段时间再继续开发新功能

**Comment by DoctorReid** [comment]
使用新版本
