### ISSUE TITLE
[需求建议] 能否增加飞宵的锄地辅助功能

### ISSUE THREAD

**Issue by yaoyan7788** [DoctorReid/StarRailOneDragon#393]
### 使用版本

2.5.1

### 当前状况

飞宵的秘籍很适合大地图锄地，范围大不需要精准的点位，只要正常跑就可以，路线上的怪物和罐子都不会漏。我的想法是增加一个自定义的计时和特殊路径（就和禁疾跑一样），进入这个路径就自动释放秘技，路径行动期间计时到了就自动放秘籍，出路径释放平A。或者简单一些增加一个自定义的计时能自动释放和续秘技，这样费零食一些。路线会比现在通用的简单，我也可以来做这个适配

**Comment by DoctorReid** [comment]
目前项目在重构中，还分不出时间做额外功能开发。

后续有这个计划

**Comment by DoctorReid** [comment]
新版本可以试试
