### ISSUE TITLE
[问题反馈] [锄大地] 拟造花萼（赤）传送落地后失控

### ISSUE THREAD

**Issue by yaoyan7788** [DoctorReid/StarRailOneDragon#398]
### 使用版本

2.6.1

### 问题分类

卡死

### 问题描述

我试了3个图的拟造花萼（赤），传送落地之后都是卡死在原地砍砍砍，视频已经发到佬你的扣扣上了

**Comment by DoctorReid** [comment]
修复了，跟传送点没关系
