### ISSUE TITLE
[问题反馈] 多账号无法切换，卡死在退出界面

### ISSUE THREAD

**Issue by manyikui** [DoctorReid/StarRailOneDragon#399]
### 使用版本

2.6.1

### 问题描述

一个账号完成任务后，再切换到下一个账号重新登陆时，卡死在退出是否保留数据界面

### 游戏截图

![屏幕截图 2024-11-11 211007](https://github.com/user-attachments/assets/69df1521-f8b9-4bfd-bdf7-569905614a66)

### 运行日志

指令[ 进入游戏 ] 节点 画面识别 返回状态 按钮-登出
指令[ 进入游戏 ] 节点 画面识别 返回状态 按钮-登出
指令[ 进入游戏 ] 节点 画面识别 返回状态 按钮-登出
指令[ 进入游戏 ] 节点 画面识别 返回状态 按钮-登出
指令[ 进入游戏 ] 节点 画面识别 返回状态 按钮-登出
指令[ 进入游戏 ] 节点 画面识别 返回状态 按钮-登出
指令[ 进入游戏 ] 节点 画面识别 返回状态 按钮-登出
指令[ 进入游戏 ] 节点 画面识别 返回状态 按钮-登出

### 你的建议

优化切换账号操作逻辑

**Comment by DoctorReid** [comment]
哪个服？我的不会弹出这个

**Comment by manyikui** [comment]
> 哪个服？ 我的不会弹出这个

国服的

**Comment by manyikui** [comment]
我是pc端的，我也在找办法关闭，我当时也不知道怎么开启的。

**Comment by DoctorReid** [comment]
修复啦，原来这是一个按玩家灰度的功能

**Comment by manyikui** [comment]
谢谢大佬！
