### ISSUE TITLE
[问题反馈] 周常未刷新

### ISSUE THREAD

**Issue by MyAngelKokkoro** [DoctorReid/StarRailOneDragon#403]
### 使用版本

2.6.1

### 问题描述

今天早上定时运行Scheduler的时候，历战余响、过期邮包、模拟宇宙三项周常未刷新，导致没有运行，不清楚是不是偶发情况

### 运行日志

[log.txt](https://github.com/user-attachments/files/17795247/log.txt)

**Comment by MyAngelKokkoro** [comment]
脚本页面截图
![image](https://github.com/user-attachments/assets/fe9a6640-0b25-4fc1-ad3c-1947d3167618)

**Comment by DoctorReid** [comment]
已修复
