### ISSUE TITLE
[问题反馈] 游戏改键之打开地图按键的改键没有了

### ISSUE THREAD

**Issue by vvincee7** [DoctorReid/StarRailOneDragon#405]
### 使用版本

2.6.1

### 问题描述

重构之前是可以进行打开地图的按键改键的qaq

### 游戏截图

![image](https://github.com/user-attachments/assets/3549b1c1-4028-42ce-afea-29f9f5001be2)

**Comment by DoctorReid** [comment]
已修复 更新代码
