### ISSUE TITLE
[问题反馈] [开拓力] 虚无行迹副本识别错误

### ISSUE THREAD

**Issue by MyAngelKokkoro** [DoctorReid/StarRailOneDragon#407]
### 使用版本

2.6.1

### 问题副本

虚无行迹 - 丹鼎司

### 问题描述

今天中午起来看的时候发现传送点在大矿区的虚无材料本，打开背包发现多了2个旧的虚无紫材料，怀疑是这俩在指南里贴的太近了导致识别错误

### 游戏截图

![H2)M8MNG6{1NF6`KFUMTGQO](https://github.com/user-attachments/assets/74ab8544-ab98-4553-b956-9cae0b7d4e06)
![`(FSURA6Q9ES1FD0B(3F%DM](https://github.com/user-attachments/assets/e00a2dc5-7a54-4390-af25-056a0c05c2d1)

### 运行日志

[log.txt](https://github.com/user-attachments/files/17912957/log.txt)

**Comment by DoctorReid** [comment]
已修复 更新代码
