### ISSUE TITLE
[问题反馈] [开拓力] 

### ISSUE THREAD

**Issue by wananZ-h** [DoctorReid/StarRailOneDragon#408]
### 使用版本

2.2.2

### 问题副本

寒潮的落幕

### 问题描述

执行完历战余响后报错，无法继续执行一条龙报错返回为识别不到返回大世界

### 游戏截图

[
![_1732619217323](https://github.com/user-attachments/assets/6136b66a-1046-4825-8657-7102b5e07e8b)
](url)

### 运行日志

[log.txt](https://github.com/user-attachments/files/17918339/log.txt)

**Comment by DoctorReid** [comment]
新版本已修复，不要使用旧版本啦
