### ISSUE TITLE
[问题反馈] [锄大地] 

### ISSUE THREAD

**Issue by ssymn** [DoctorReid/StarRailOneDragon#411]
### 使用版本

StarRail-OneDragon-2.6.1

### 问题分类

卡死

### 问题描述

無法效准成功
![55e3e8f9ec643c0b8c722e786665b71c](https://github.com/user-attachments/assets/cc679d51-06f0-4baa-a803-d171a6458b75)

### 游戏截图

![55e3e8f9ec643c0b8c722e786665b71c](https://github.com/user-attachments/assets/523127ef-2c2f-4691-afb9-291ef3c59aed)

### 运行日志

指令[ 传送 空间站黑塔 基座舱段 接待中心 ] 节点 检测游戏窗口 返回状态 成功
指令[ 打开地图 ] 节点 检测游戏窗口 返回状态 成功
尝试打开地图
指令[ 打开地图 ] 节点 画面识别 返回状态 等待
当前大地图所处星球 04 - 匹诺康尼
指令[ 打开地图 ] 节点 画面识别 返回状态 成功
指令[ 打开地图 ] 执行成功 返回状态 成功
指令[ 传送 空间站黑塔 基座舱段 接待中心 ] 节点 打开地图 返回状态 成功
指令[ 选择星球 空间站黑塔 ] 节点 检测游戏窗口 返回状态 成功
当前在大地图 准备选择 星轨航图
指令[ 选择星球 空间站黑塔 ] 节点 选择 返回状态 星轨航图
当前在星轨航图
指令[ 选择星球 空间站黑塔 ] 节点 选择 返回状态 重试
当前在星轨航图
指令[ 选择星球 空间站黑塔 ] 节点 选择 返回状态 重试
当前在星轨航图
指令[ 选择星球 空间站黑塔 ] 节点 选择 返回状态 等待
指令[ 选择星球 空间站黑塔 ] 节点 选择 返回状态 成功
指令[ 选择星球 空间站黑塔 ] 执行成功 返回状态 成功
指令[ 传送 空间站黑塔 基座舱段 接待中心 ] 节点 选择星球 返回状态 成功
指令[ 选择区域 基座舱段 ] 节点 检测游戏窗口 返回状态 成功
指令[ 选择区域 基座舱段 ] 节点 检测星球 返回状态 成功
当前区域文本 主控舱段 匹配区域名称 主控舱段
指令[ 选择区域 基座舱段 ] 节点 选择区域 返回状态 重试
当前区域文本 基座舱段 匹配区域名称 基座舱段
指令[ 选择区域 基座舱段 ] 节点 选择区域 返回状态 成功
指令[ 选择楼层 0 ] 节点 检测游戏窗口 返回状态 成功
指令[ 选择楼层 0 ] 节点 画面识别 返回状态 成功
指令[ 选择楼层 0 ] 执行成功 返回状态 成功
指令[ 选择区域 基座舱段 ] 节点 选择楼层 返回状态 成功
指令[ 选择区域 基座舱段 ] 节点 主区域缩放地图 返回状态 无需缩放
指令[ 选择区域 基座舱段 ] 节点 选择子区域 返回状态 非子区域无需操作
指令[ 选择区域 基座舱段 ] 节点 子区域缩放地图 返回状态 非子区域无需操作
指令[ 选择区域 基座舱段 ] 执行成功 返回状态 非子区域无需操作
指令[ 传送 空间站黑塔 基座舱段 接待中心 ] 节点 选择区域 返回状态 非子区域无需操作
指令[ 选择传送点 接待中心 ] 节点 检测游戏窗口 返回状态 成功
匹配大地图失败
拖动地图 (1350, 800) -> (1150, 600)
指令[ 选择传送点 接待中心 ] 节点 画面识别 返回状态 重试
匹配大地图失败
拖动地图 (1350, 800) -> (1550, 1000)
指令[ 选择传送点 接待中心 ] 节点 画面识别 返回状态 重试
匹配大地图失败
拖动地图 (1350, 800) -> (1550, 600)
指令[ 选择传送点 接待中心 ] 节点 画面识别 返回状态 重试
匹配大地图失败
拖动地图 (1350, 800) -> (1150, 600)
指令[ 选择传送点 接待中心 ] 节点 画面识别 返回状态 重试
匹配大地图失败
拖动地图 (1350, 800) -> (1150, 600)
指令[ 选择传送点 接待中心 ] 节点 画面识别 返回状态 重试
匹配大地图失败
拖动地图 (1350, 800) -> (1550, 1000)

### 你的建议

不知道如何解決

**Comment by DoctorReid** [comment]
周末两天可以QQ联系我远程看看

F11上传游戏截图才能判断问题 我觉得应该是有遮挡导致的
