### ISSUE TITLE
[问题反馈] 

### ISSUE THREAD

**Issue by telZhongshiji** [DoctorReid/StarRailOneDragon#412]
### 使用版本

2.6.1

### 问题描述

刷模拟宇宙能被4点月卡卡死

其次还有连世界9都寻路有问题，建议枚举路线，按第一间进去的环境识图来走预设线路。
“飞霄模式”的按钮也没有，我开“用秘技”结果是阮梅模式，EAAAA，当场浪费1秘技点。
还有识路不行就直接退出了，打boss前还好，打过boss再退会减少刷第三个boss的次数（总boss限额是100个）。应当临时退，重进，刷新位置。

**Comment by DoctorReid** [comment]
虽然建议很好，但都没法解决

1. 世界9没有小地图，所以没有预设路线
2. 模拟宇宙未支持飞霄
3. 识路失败是没办法提前感知失败的，这是概率事件，所以没法提前退出
4. 月卡问题可以另开一个issue上传截图
