### ISSUE TITLE
[问题反馈] 一条龙bug

### ISSUE THREAD

**Issue by lingyu20** [DoctorReid/StarRailOneDragon#413]
### 使用版本

2.6.1

### 问题描述

1新版经常性重复打开菜单又关闭（但无任何后续）（校准过依旧）这两天看着日常和委托都是红点然后手动清
2任务列表是否是越往上越优先执行如果是那就是bug不是就算了，我把清委托排到最上结果先执行的是开拓力
3任务列表的任务完成检测有偏差，出现重复打开菜单也算任务执行完成了，建议加一个强制执行模式将√的任务也再次运行

### 运行日志

[log.txt](https://github.com/user-attachments/files/18105527/log.txt)

**Comment by lingyu20** [comment]
今日持续重复开关菜单中，连任何任务都无法执行了，只会开菜单。画面1920*1080，游戏助手已校准
![_1734070958547](https://github.com/user-attachments/assets/2a43d915-d44c-4f4a-a2f3-0ebce4d3dc1a)
![_1734070960289](https://github.com/user-attachments/assets/e7c905f0-2135-40c2-b047-a92be5213977)

**Comment by lingyu20** [comment]
[Uploading log.txt…]()

**Comment by lingyu20** [comment]
![Uploading 程序.png…]()

**Comment by lingyu20** [comment]
找到疑似原因的问题，程序尝试打开菜单的判定过快导致指令执行而菜单还没完全展开就已经开始重试，建议给指令速度加一个自定义延时0.5-3秒

**Comment by DoctorReid** [comment]
2,3 应该都是1引起的。1修复了；2，3再遇到再提新issue
