### ISSUE TITLE
[问题反馈] 切换账号登录时，点击同意《用户协议》勾选时卡住

### ISSUE THREAD

**Issue by RedRedCatCat** [DoctorReid/StarRailOneDragon#415]
### 使用版本

2.6.1 c0602f4

### 问题描述

同步到12月14号代码后，选择运行全部实例，自动切换账号登录时，
**在点击勾选：同意《用户协议》时会卡住** （无法正常勾选）

1.国服，PC端
2.用其他PC设备测试，同步到12月14号的代码更新后都会出现切换账号点击勾选时卡住
3.尝试回滚到12月04号的代码后还是勾选卡住
辛苦老大核实检查一下！

### 游戏截图

![_1734405090905](https://github.com/user-attachments/assets/66d98500-7712-41b8-bd05-1a1338130371)

### 运行日志

[log.txt](https://github.com/user-attachments/files/18159703/log.txt)

**Comment by RedRedCatCat** [comment]
喔嚯，还真是，3台PC设备共截图到2种登录界面，开了眼了
![_1734446038494](https://github.com/user-attachments/assets/1821bc54-c229-4d23-99b4-3d5254489a83)
![EnterGame_1734405864706](https://github.com/user-attachments/assets/b570230d-fca0-43e8-ab08-07503829f5da)

**Comment by DoctorReid** [comment]
因为我的账号已经被灰度到用新的登陆方式了，这个尝试修复了下，没法测试，你试试再反馈

**Comment by RedRedCatCat** [comment]
感谢老大修复，已更新到f1d4e9e，两种登录模式都测试正常！

**Comment by RedRedCatCat** [comment]
> 因为我的账号已经被灰度到用新的登陆方式了，这个尝试修复了下，没法测试，你试试再反馈

感谢老大修复，已更新到f1d4e9e，两种登录模式都测试正常！
