### ISSUE TITLE
新增托帕使用秘技点进场。

### ISSUE THREAD

**Issue by yinghaodang** [DoctorReid/StarRailOneDragon#96]
我有个想法。
托帕使用秘技进场可以每天多拿一些信用点。那么在map的配置文件中添加一行，比如说这样：
![image](https://github.com/DoctorReid/StarRailAutoProxy/assets/49315320/42189b11-598f-4f6a-9071-ac3b974a198b)
这个recipe可以添加在任何一行，表示按E使用秘技点。
同时支持多带data参数
![image](https://github.com/DoctorReid/StarRailAutoProxy/assets/49315320/d73f91a2-715a-4023-9587-72469da4d780)
这个表示在游戏内"奇巧零食"的位置，这个位置可以交给用户自己维护，ScreenRuler这个工具能获得游戏内的像素点的位置。或者后期这类秘技有收益的角色多的话，可以再绘制一些黑白图去进行模板匹配...
为什么是"奇巧零食"？因为便宜，大家都能轻松合成，其他的道具，需要钱买，甚至没有多余获得方式，还是有一定收藏价值的，特别是"垃圾桶的尊严"。

还有第二个想法，在地图绘制这个功能里有一个优化点。
鼠标悬浮在左边地图上可以获取游戏内的坐标。

正在阅读大佬代码ing, 膜拜一下。

**Comment by DoctorReid** [comment]
1. 秘技和道具使用功能需要花时间先整体想想
2. 目前使用习惯是直接点一下，然后在右边输入框里复制粘贴

**Comment by UU0510** [comment]
秘技点用完之后按e有快速恢复, 我的想法是在每个'patrol'后面添加一个使用秘技的模块, 按e, 然后检测有没有弹出快速恢复界面, 如果没有弹出就继续锄地, 如果弹出就依次点击一次确定和取消然后再按e再继续锄地, 然后加个计数功能, 可以设定使用多少次秘技后不再使用. 大佬看看有没有可能实现

**Comment by DoctorReid** [comment]
#185 中会实现
